### ISSUE TITLE
Error 404 when opening server URL on Linux

### ISSUE THREAD

**Issue by TronFortyTwo** [ahmadomar/ScreenTask#9]
ScreenTask says "Server started succeffully" but when I open the URL I got a Server error 404 message.
Both on LAN wifi and on lo at 127.0.0.1. The window doesn't dislay any error message, but in the terminal I read this:
`[emanuele@smartkeyboard Screen Task]$ java -jar ScreenTask.jar

java.io.FileNotFoundException: /home/emanuele/Desktop/Screen%20Task/WebServer/ScreenTask.jpg (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at javax.imageio.stream.FileImageOutputStream.<init>(FileImageOutputStream.java:69)
	at com.sun.imageio.spi.FileImageOutputStreamSpi.createOutputStreamInstance(FileImageOutputStreamSpi.java:55)
	at javax.imageio.ImageIO.createImageOutputStream(ImageIO.java:419)
	at javax.imageio.ImageIO.write(ImageIO.java:1530)
	at screentask.ScreenShot.takeScreenshot(ScreenShot.java:78)
	at screentask.ScreenThread.run(ScreenThread.java:30)
Apr 24, 2017 5:56:27 PM screentask.ScreenThread run
SEVERE: null
java.lang.NullPointerException
	at javax.imageio.ImageIO.write(ImageIO.java:1538)
	at screentask.ScreenShot.takeScreenshot(ScreenShot.java:78)
	at screentask.ScreenThread.run(ScreenThread.java:30)`

**Comment by Rishats** [comment]
Same problem.

**Comment by ahmadomar** [comment]
Thanks for your notification, let me check it and inform you after finishing 👍

**Comment by thiru112** [comment]
@TronFortyTwo @Rishats  I also had the same problem , but got resolved when you extract the **zip**  file there will **webserver** file  put this file and ScreenTask.jar in same location problem resolved

**Comment by ahmadomar** [comment]
@TronFortyTwo @Rishats try to extract the file in the same location of ScreenTask.jar

Thanks @thiru112

**Comment by kevinesaa** [comment]
I solved this issue replacing space by underscore of the path

**Comment by ahmadomar** [comment]
Resolved by @kevinesaa
